### ISSUE TITLE
Problems with qr code generation

### ISSUE THREAD

**Issue by t78Linux** [andrepatta/electroneum-gui#1]
There is a problem with the file 
./pages/Receive.qml Line 75

`var s = "monero:"` should be:
`var s = "electroneum:"`
Already compiled and it works, having electroneum: defined as var s is not a problem as I thought before.

**Comment by andrepatta** [comment]
Issue fixed by commit 7710e32cb2fc6034ca5de2e721d64717e5d79569

Thanks for the contribution!
